### ISSUE TITLE
[branch-data_analysis] A private opinion about exploring us_beef_production data for Jimin.

### ISSUE THREAD

**Issue by iamcodingcat** [DSC-SCH/livestock-solution-project#1]
우선적으로 연도/월 별로 미국 소고기에 대한 시각화를 잘하신 것 같습니다! 연도별로 하나씩 그래프로 시각화한 것 뿐만 아니라 하나의 그래프에 연도별로 가격 추이 그래프 추세를 나타내는 것도 좋았습니다.

개인적으로 바라는 사항이 있다고 하면 저희가 목표로한 해당 기간년도 2013~2018 데이터를 뽑아내실 때 2013~2018년도 데이터만 추출 이런식으로 주석으로 간단하게 설명을 해주시면 다른사람이 이해할 때 훨씬 더 빠르고 직관적으로 이해할 수 있을 것 같습니다! (설명 한 줄 보고 코드를 읽으면 훨씬 더 빨리 읽히더라구요! - 지극히 개인적인 의견입니다 ㅠ ) 

그리고 남은 기간까지 여유가 있으시다면 해당 데이터로부터 또 다른 관점에서 시각화해볼만한 요소들이 있는지 생각해보셔도 되고 또는 그래프 추이를 보시고 가격이 어떤 시점만 내려갔다면 그 때는 왜그랬는지 지민님만의 다양한 추론을 하셔도 좋을 것 같습니다! 또한 여러가지 그래프를 그려봄으로써 다양한 시도를 해주신다면 저희가 발견하지 못한 부분도 함께 발견할 수 있을 것 같아요! 

EDA 하시느라 고생 많으셨습니다! 저도 빨리 하고 올리겠습니다!!!

**Comment by parkseonga** [comment]
저도 영훈님의 의견에 동의합니당!! 개인적으로 시각화 결과에 대한 지민님의 생각을 함께 달아놓으시면 더 좋을 것 같아요! 고생하셨습니당:)
