### ISSUE TITLE
[db_relation] diagram  

### ISSUE THREAD

**Issue by jjimini98** [DSC-SCH/livestock-solution-project#11]
### DB_Digram

![livestock (1)](https://user-images.githubusercontent.com/46179699/82948260-6edfbe80-9fdc-11ea-8cea-7965ecc0d39c.png)

```
Table user{

 user_id int [pk] 
  user_nickname varchar(100) [NOT NULL]
  kakaoID varchar(100)
  profile_photo longblob
  address varchar(255) [NOT NULL]
  cow_count int 
  phone_num char(11)
  user_type int [NOT NULL]
  introduction varchar(255)
  created_date date [NOT NULL]
  last_modified_date date [NOT NULL]
 
} 
```

칼럼 | 타입 | 옵션 | 설명 
------|------|------|------
user_id  | int | PK | 사용자의 아이디 
user_nickname | varchar | NN | 사용자의 닉네임
kakaoID | varchar | nullable | 카카오톡 아이디 ( 소셜 로그인) 
profile_photo | longblob | nullable | 프로필 사진 
address | varchar | NN | 농가의 주소
cow_count | int | nullable | 사육두수 
phone_num | char(11) | nullable | 휴대폰 번호 또는 농가 연락처 
user_type | int | NN | 축산농가(1)인지 예비농가(2)인지
introduction | varchar | nullable | 소개글 
created_date | date | NN | 첫 생성 날짜
last_modified date | date | NN | 최종 수정 날짜 

- *이미지 사이즈는 정하지 않아도 괜찮은건지?*
- *앱 사용 연령층을 고려해본다면 , 소셜 로그인 방법 뿐 아니라 다른 방법도 있으면 좋다고 생각* 
 
```
Table price {
  sales_price float [NOT NULL]
  operationing_price int 
  material_price int 
  created_date date [NOT NULL]
  last_modified_date date [NOT NULL]
}
```

칼럼 | 타입 | 옵션 | 설명 
------|------|------|------
sales_price | float |NN | 주차별 시세
operationing_price | int  | nullable  | 평균경영비 
material_price | int  | nullable  | 평균사료(재료)비
created_date | date | NN | 첫 생성 날짜
last_modified date | date | NN | 최종 수정 날짜 

```
Table community {
  //nickname varchar(255) FK
  favorite_farm_id int 
  tag vachar 
  post_id varchar(5) [NOT NULL}
  like varchar(5) 
  save varchar(5)
  comment varchar
  created_date date [NOT NULL]
  last_modified_date date [NOT NULL]
}
```

칼럼 | 타입 | 옵션 | 설명 
------|------|------|------
favorite_farm_id | int | nullable | 관심농가 
tag | varchar |  nullable |  태그 설정
post_id |  varchar(5) | NN  |  글아이디 (포스팅된 글에 부여하는 번호) 
like |  varchar(5) |  nullable |  '좋아요' 누른 글 
save |  varchar(5) |  nullable |  '스크랩' 한 글 
comment |  varchar |  nullale |  댓글 
created_date | date | NN | 첫 생성 날짜
last_modified date | date | NN | 최종 수정 날짜

- *그냥 post_id 없이 해도 괜찮을까요? 제가 생각했을 땐 그냥 varchar로 타입 지정해서 만들면 오히려 비효율적일거라 생각했어요. 글마다 id를 매기고 그 id로 '좋아요 한 글' 과 '저장한 글' 을 저장할 수 있게 하는게 더 나을 거 같아서요. 의견이 궁금합니다.* 

```
ref: user.user_id < community.favorite_farm_id
ref: user.user_id < community.save
ref: user.cow_count - price.material_price
ref: user.cow_count - price.operationing_price
```
- *이 툴(dbdiagram.io)에서 FK 설정하는 방법을 제가 못찾는건지.. 구글링을 해도 찾을 수가 없네요... 흠 다시 찾아보고 발견하면 수정해두겠습니다*

* 링크 : https://dbdiagram.io/d/5eccf82339d18f5553ffc5a3

**Comment by NDjust** [comment]
@jjimini98 코멘트도 각 유저마다 생성을 하는 것이기 때문에 table을 하나 빼면 좋을 거 같아요. 그리고 PK값 명시와 post_id 경우 varchar가 아니라 PK로 잡아서 bigint 타입으로 지정하는게 좋을 거 같아요:)

질문 게시판에 대한 Table이 없네요!

**Comment by NDjust** [comment]
cow_count의 경우  10~100 이런식으로 범주로 나누기 때문에 아마 자료형을 varchar로해서 |구분자로 빼서 구분한 후 그에 맞게 릴레이션을 구성하는게 좋을 거 같습니다.

**Comment by NDjust** [comment]
User

- PK 명시
- cow_count와 price 관게 설명
- Introduction 타입 -> varchar가 아닌 text로 하는게 좋지 않을까요?? 
- 관심 농가에 대한 로직에 대해서 한번 더 고민 해보시면 좋을 거 같아요.

Community
- Favorite_fram_id 이거는 community table에서 로직이 생기보단 유저끼리 생기는 관계라고 생각이 드네요.
- Save 필드는 보든 스크랩에 대한 명시적인 네이밍이 필요할 거 같고, 스크랩은 해당 유저가 community에 있는 포스트를 스크랩 하는 것이기 때문에 save가 community 필드에 있으면 유저 입장에서 스크랩한 community 글을 어떻게 가져와야 할까요?? 만약 community에 필드를 둔다면 있다면, save_users로 해당 글을 스크랩한 유저들은 담은 필드여야지 로직이 맞을 거 같네요.
- community에 등록되는 내용과 사진에 대한 필드가 업네요. 그리고 community라는 것이 이름 자체가 너무 포괄적이고 community_post와 같이 세부적으로 가는 것 도 좋을 거 같아요.
- price이름도 마찬가지구요. 만약에 해당 앱에서 다른 price에 대한 테이블이 들어온다고 가정하면 확장성이 너무 떨어지는 설계입니다.

질문 게시판
- 해당 테이블도 필요할 거 같습니다.

**Comment by jjimini98** [comment]
### 피드백 반영해야할 것 

- [x] comment(댓글) table 생성 

- [x] post_id  -> 타입변환 (bigint)

- [x] 질문게시판 table 생성 

- [x] cow_count 

- [x] user 테이블 cow_count 와 price 관계설명 
 
- [x] user 테이블의 introduction 타입변환 text

- [x] 관심농가 로직 다시 

- [x] community table 에 내용과 사진에 대한 필드추가 

- [x] Save 필드의 위치수정 

- [x]  community table을 조금 더 나눠야할듯 

- [x] price table 생각 다시

**Comment by jjimini98** [comment]
### DB Diagram (edited) 

![livestock](https://user-images.githubusercontent.com/46179699/83067978-7ec1d600-a0a2-11ea-9039-426c93e1b632.png)


```
table user {
  user_id int [pk]
  user_name varchar(100) [NOT NULL]
  kakao_id varchar
  address varchar(80) [NOT NULL]
  tel varchar(13)
  user_type boolean [NOT NULL]
}
```
칼럼|타입|옵션|설명
------|------|------|------
user_id  | int | PK | 사용자의 아이디 
user_name | varchar | NN | 사용자의 닉네임
kakao_id | varchar | nullable | 카카오톡 아이디 ( 소셜 로그인) 
address | varchar(80) | NN  | 농가주소 
tel  | varchar(13)  | nullable  | 전화번호 
user_type  | boolean  | NN  | 예비농가인지 축산농가인지 

```
table mypage {
  user_id int [pk]
  user_name varchar
  profile_photo longblob
  cow_count varchar [NOT NULL]
  introduction text
  scrap text 
}
```

칼럼|타입|옵션|설명
------|------|------|------
user_id  | int | PK | 사용자의 아이디 
user_name | varchar | NN | 사용자의 닉네임
profile_photo | longblob | nullable | 사용자의 프로필 사진 
cow_count | varchar | NN | 사육두수 
introduction | text | nullable | 소개글 
scrap | text | nullable | 스크랩한 글 보기 

```
table favorite_farm {
  user_id int [NOT NULL] 
}
```

칼럼|타입|옵션|설명
------|------|------|------
user_id | int | NN | 사용자의 아이디 

```
table price {
  sale_price float [pk]
  operating_price float 
  feed_price float
}
```

칼럼|타입|옵션|설명
------|------|------|------
sale_price | float | NN | 판매가격
operating_price | float | nullable | 평균운영비
feed_price | float | nullable | 평균재료비 

```
table question {
  question_id bigint [pk]
  question_photo longblob
  question_contents text [NOT NULL]
  }
```

칼럼|타입|옵션|설명
------|------|------|------
question_no | bigint | NN | 질문게시판글 번호 
question_photo| longblob | nullable | 질문 게시판 사진 
question_contents | text | NN | 질문 게시판 글 

``` 
table community{
  community_id bigint [pk]
  community_photo longblob 
  community_contents text [NOT NULL]
}
```

칼럼|타입|옵션|설명
------|------|------|------
community_no | bigint | NN | 커뮤니티글 번호 
community_photo | longblob | nullable | 커뮤니티 사진
community_contents | text | NN | 커뮤니티 글 

```
table react {
  no bigint [pk]
  view int 
  like int 
  scrap int 
  comment text 
}
```
칼럼|타입|옵션|설명
------|------|------|------
no | bigint | NN | 글의 번호 
view | int | nullable  | 글의 조회수
like | int | nullable | 좋아요 수 
scrap | int | nullable | 스크랩 수 
comment | text | nullable | 댓글 

```
ref: question.question_no < react.no
ref: community.community_no < react.no 
Ref: "user"."user_id" - "mypage"."user_id"
Ref: "mypage"."cow_count" -  "price"."operating_price"
Ref: "price"."feed_price" - "mypage"."cow_count"

```
-*mypage 테이블의 cow_count( 사육두수) 와 price 테이블의 operating_price(평균운영비) 와 feed_price(평균재료비) 사이에 관계가 있다고 판단*
-*question테이블과 react테이블, community테이블과 react테이블 간 관계가 있다고 판단*
-*링크 : https://dbdiagram.io/d/5eccf82339d18f5553ffc5a3*

-*관심농가는 정말 잘 모르겠어요,,도와주세요 엉엉*

**Comment by NDjust** [comment]
@jjimini98 

DB Relation 피드백
- question, community, react 분리한 후 fk로 id 값을 가져오면,  int형이기 때문에 문제 발생.
    - 만약 이렇게 분리하고 싶으면 post_type 필드 만들어서 어떤 카테고리의 post인지 구분을 해야함.
- myPage랑 price랑 매핑 관계는 의미가 없는듯합니다. price는 그냥 Table에서 각 사유두수를 CowRange로 해서 나눠서 저장하면 될 거 같아요.

지민님이 작성해주신 내용 바탕으로 1차 수정했습니다. 최종은 같이 만나서 정리해서 수정하면 될 거 같아요. 너무 고생하셨어요!

https://dbdiagram.io/d/5ecf5d2d39d18f5553ffe0c8


수정된 내용 이해 안되시는 부분 있으시면, 코멘트 남겨주세요.

**Comment by jjimini98** [comment]
@NDjust 

확인했습니다 ! 저 relationship 테이블에서 action_user_id는 어떤건지 궁급합니다

**Comment by NDjust** [comment]
@jjimini98 관심 농가를 누른 유저라고 보시면 됩니다! 즉 relation을 실행한 유저입니다.

+ user_one 이랑 action 유저가 같은 유저이긴 하니 명시적으로 필드를 추가해 구분 해놨습니다

**Comment by NDjust** [comment]
### DB 설계 2차 최종
---

![2차_최종](https://user-images.githubusercontent.com/47904523/83235333-ad3bd000-a1cc-11ea-8655-c5cfbb500643.png)



[링크](https://dbdiagram.io/d/5ecf5d2d39d18f5553ffe0c8)
