### ISSUE TITLE
[data_EDA] A private opinion about exploring us_beef_production data for Nathan.

### ISSUE THREAD

**Issue by parkseonga** [DSC-SCH/livestock-solution-project#2]
EDA 해주신 것 잘보았습니다! 가축사육현황 분석에서 '마리수-번식우', '번식우가 아닌 소 중 1세 미만(암, 수) 제외' 변수를 생성하여 이에 관한 상관성 분석도 부탁드립니다! 마리수의 경우 상관성이 정말 낮네요,,,

**Comment by parkseonga** [comment]
경매가격(y값)과 관계를 분석하실 때 경매금액이 0인 부분도 포함하신 것으로 보입니다. 경매금액이 0인 부분은 필요가 없는 부분으로 간주됩니다. 제외하고 추가 분석 부탁드립니다!

**Comment by NDjust** [comment]
@parkseonga [](url)
수정 및 추가 사항

- 경매금액 0인 부분 삭제 후 진행
- "마리수-번식우 ", "번식우가 아닌 소 중 1세 미만(암, 수) 제외" 칼럼 만들어서 상관분석 진행
맞나요?

- 마리수-번식우 라는것에 대한 설명 부탁드립니다. 마리수-번식우 변수를 묶으라는건지 이해가 안되네요.

**Comment by parkseonga** [comment]
'번식우가 아닌 소' 라고 생각하시면 될 것 같습니다. 마리수 변수에서 번식우 변수를 뺀 변수를 생성하여 한우 평균 경매 금액과 상관성을 확인하기 위함입니다. 상관성이 더 높은 변수를 택하기 위함인데 분석 결과 상관성이 거의 낮아 이것도 그럴 것 같긴 하지만 확인해보고자 합니다!

**Comment by NDjust** [comment]
test

**Comment by NDjust** [comment]
네 확인했습니다.

가축현황 EDA 수정 및 추가 사항

- 경매금액 0인 부분 삭제 후 진행
- "번식우가 아닌 소", "번식우가 아닌 소 중 1세 미만(암, 수) 제외" 칼럼 만들어서 상관분석 진행

**Comment by NDjust** [comment]
@parkseonga  위 피드백 내용 반영 했으니 확인 부탁드릴게요.

**Comment by NDjust** [comment]
@parkseonga 
피드백 주신 부분 중에 평균 경매 금액 =0에 대한 데이터를 지우고 진행 하니 상관계수 값들이 큰 폭으로 달라져서 이점 한번 참고해서 확인 부탁드릴게요.

**Comment by parkseonga** [comment]
확인했는데 번식우가 아닌 소에서 1세 미만 암+수 소 현황을 제외한 부분이 번식우 보다 값들이 더 크더라구요 제가 코드를 다 한 번씩 돌렸어서 결과는 다시 도출해냈는데 그래도 시간되실 때 코드 수정부탁드려요!!
