### ISSUE TITLE
[data_EDA] 축산물 실시간 경매시황중계정보 EDA 피드백(성아)

### ISSUE THREAD

**Issue by NDjust** [DSC-SCH/livestock-solution-project#3]
@parkseonga 
- https://github.com/DSC-SCH/livestock-solution-project/blob/data_EDA/eda/hanwoo_and_pig_price_holiday.ipynb

연휴와 소 경매가 날짜와의 관계 볼때 Smoothing 하고 봐도 좀 좋을 거 같아요. 
그리고 추가로 소 경매가 스무싱된 그래프도 한번 보면 좋을 거 같아요.

**Comment by parkseonga** [comment]
넹 확인하였습니당 :)
