### ISSUE TITLE
[data_EDA] 구제역 데이터 EDA 추가 의견 및 피드백 (영훈)

### ISSUE THREAD

**Issue by NDjust** [DSC-SCH/livestock-solution-project#4]
구제역 데이터랑 y값이랑 날짜 맞춰봐서 확인하면 좋을 거 같아요. 

성아님 분석하신것 중에 튀는 값들이 구제역 날짜일 수도 있다는 생각이 드네요.

근데 추가로 구제역 같은 부분은 "에측 불가능한 영역"이라서 의미가 없을 거 같긴 하네요.

**Comment by iamcodingcat** [comment]
네넵! 현재 저 진행상황에서 질병별로 y값(경매가격)과의 상관성 분석하고 있습니다! 끝나는대로 바로 커밋하겠습니다!

**Comment by iamcodingcat** [comment]
질환과 상관성 분석 진행완료 후 커밋했습니다!

**Comment by parkseonga** [comment]
추가 분석한 내용 확인하였습니다!

 개인적으로 뚜렷하게 특정 월이 높은 것이 아니기 때문에 월별로 가중치를 주지않아도 될 것 같습니다. **질병 발생 유무**로 변수를 넣는게 좋을 것 같아요. 질병 발생 후 몇 일까지 유로 가정하여 파생변수를 생성하는 것에 대해 어떻게 생각하시나요? 결핵병, 브루셀루나병, 구제역 각각 나눠서 하셨는데 **질병 전체에 대한 관계**도 궁금합니다.

 연도나 월의 경우 독립변수로 사용할 수 있는 값들이 아니기 때문에 연속형변수들과 상관성 분석을 하는 것은 적합하지 않다고 생각합니다. 연도나 월은 기준점? 이라고 할까요?..? 추세를 본다거나 계절성을 보는 등 연도별 월별 차이를 알아내는 변수로는 매우 적합하나 통계적 관계를 보기엔 부적절한 변수인 것 같아요!

 대표값으로 주로 평균이나 중앙값, 최빈값을 사용하는 것으로 알고 있었습니다. 합을 이용하는건 모호하다고 생각이 드는데 합을 사용하여 분석하신 이유가 궁금합니다!

그리고 개인적으로 중앙값과 분석한 결과도 있으면 좋을 것 같아요:)

날씨 기준으로 보았을 때 날씨 데이터 값들이 돼지 탕박경매 금액과 상관성을 갖고 있네요!! 돼지 탕박경매 금액은 한우 평균 경매 금액과도 상관성을 띄고 있는데 한우 평균경매 금액과 날씨 데이터는 그에 비해 적은 상관성을 띄는게 흥미롭고 두렵네요. 전체 데이터로 EDA를 아직 해보지 않아 확신할 순 없지만 날씨와 돼지탕박가격처럼 독립변수로 사용할 값들 사이에서 상관성이 높은 변수들이 꽤 존재한다면 다중공선성 문제가 신경쓰일 수 있을 것 같아요.   

마지막에 물어보신 것에 대해서 개인적인 의견을 말씀드리자면 연도가 지날수록 소의 경매금액이 올라가는 건 상관분석이 아니라 시각화를 통해 결론을 도출해내는 것이 맞다고 생각합니다. 제가 EDA한 결과를 보시면 연도가 지남에 따라 상승하는 추세를 보이다 2017년, 2018년에 하락하더라구요 이런식으로 경매금액은 당연히 오르는 건 아닐 수 있다고 보입니다!

**Comment by iamcodingcat** [comment]
아하! 자세한 피드백 감사합니다! 피드백에 대한 답변 리스트로 열거해서 답변드리겠습니다!
1. 질병 발생 유무로 변수 넣는 아이디어 -> 매우 괜찮은 생각입니다!! 바로 추가적으로 시행해볼게요!
2. 연도와 월 이라는 독립변수 -> 아하! 그렇군요. 새로운 사실을 알아갑니답..!
3. 합계를 사용한 이유+중앙값 아이디어-> 사실 특별한 생각을 한게 아니고 다양한 관점에서 접근해보자 했었는데 제가 통계학에서의 대푯값을 생각을 못했습니다..! 그래서 합계와의 상관성 삭제 후 중앙값과의 상관성 추가적으로 하겠습니다!
4. 연도와 경매가격의 상관성 -> 상관성보다는 시각화하는 것이 알맞을 것 같네요! 앞으로 EDA할 때 다른 분들이 EDA하신 것들 더욱 더 자세하게 참고해야 할 거 같아요! 감사합니다 :)

**Comment by iamcodingcat** [comment]
피드백 받은 후 추가적으로 관계성 분석해서 커밋했습니다! 추가적으로 작업한 사항은 다음과 같습니다. 기존 코드에 이어 밑에다가 추가적으로 작성했고 목차 중 **'2 피드백 수정 부분'** 보시면 됩니다!

1. 질병 발생 유무와 한우 평균경매가격의 '평균'값, '중앙'값과의 관계성 파악
2. 질병 발생 유무와 돼지 탕박 경매 가격의 '평균'값, '중앙'값과의 관계성 파악
