### ISSUE TITLE
[data_analysis] 분석 및 시각화 결과

### ISSUE THREAD

**Issue by NDjust** [DSC-SCH/livestock-solution-project#5]
https://github.com/DSC-SCH/livestock-solution-project/blob/data_analysis/worldImport.ipynb

위 분석하신 내용에서 추가로 수정하시면 좋을 부분 있어 의견 남깁니다.

1. 분석별 간단 설명 
    - 이 부분은 영훈님이 피드백을 주셨겠지만 각 분석한 데이터별 간단한 설명 이후에 분석이 진행되면 가독성 측면에서 좋을 거 같습니다.
2. 시각화 크기 조절 & 새로운 유형의 시각화 추가 설명
    - 대부분 시각화 하신게 사이즈가 일정한데, 몇몇 그래프는 보기 힘든 그래프도 있습니다다. 아래 그래프 같은 경우 알아보기가 좀 힘드네요. 
    - 누적영역형 그래프를 그려주셨는데 해당 그래프가 어떤 의미이고 어떤 목적으로 사용하셨는지 설명 추가 해주시면 좋을 거 같습니다.
          - ![image](https://user-images.githubusercontent.com/47904523/79857448-c3ee4a80-8408-11ea-8ed4-88468087f094.png)

**Comment by iamcodingcat** [comment]
우선 분석하시느라 고생하셨습니다! 코드의 마지막 부분에서 상관성 분석을 통해 연도가 지날 수록 냉동, 냉장 모두 증가하는 상관성을 알 수 있었습니다. 

그리고 나단님이 제공하셨던 피드백 이외에 한 가지만 말씀드리겠습니다! 현재 지민님께서 할당받으신 데이터 안에서는 충분히 탐색적 분석을 하신 것 같아 '한우 경매 가격(y값)' 과의 상관성도 분석해보시면 좋을 것 같습니다! 

만약 한우 경매 가격 데이터 포맷 처리를 직접 하기 까다로우시다면 저, 성아님, 나단님이 분석하신 파일의 코드를 카피 코딩하셔서 시도해보시면 좋을 것 같습니다!

**Comment by parkseonga** [comment]
저도 데이터 내  탐색은 충분해보입니다.

미국 소 가격과 y값인 실시간 한우 평균 경매 금액 관계에 대한 scatter plot과 상관성 분석, 연도별 월별  boxplot, 한 그리드 내 두 변수의 lineplot을 통해 변화 추이를 함께 볼 수 있으면 더욱 좋을 것 같습니다. 

수입 현황에 관한 냉장, 냉동, 계에 대한 내용도 동일합니당!

혹시나 시간적으로 부담되신다면 scatter plot과 상관성분석, lineplot정도만 해주셔도 괜찮을 것 같아요!

고생하셨습니당:)
