### ISSUE TITLE
[data_EDA] 변수 데이터 칼럼처리와 병합

### ISSUE THREAD

**Issue by iamcodingcat** [DSC-SCH/livestock-solution-project#6]
시험기간 종료 후 오랜만에 변수 데이터를 살펴보니 헷갈리는 게 많았습니다. 이전에 저희가 공유했던 Feature별 EDA에 기반해서 각 데이터마다 필요하다고 생각되지 않는 칼럼들을 제거하고 병합을 시도했습니다. 파일명은 'all_merged_data.ipynb'  이며 해당파일 봐주시면 됩니다.

<해당 파일 보시면서 피드백 주셔야할 점들>
1. Feature별로 제거한 데이터 칼럼들 중에서 중요도가 높은 칼럼인데 제가 실수로 drop한 칼럼이 있는지 여부
2. 전처리 한 부분(y값 가격의 값을 소수 둘째자리까지만 출력, 칼럼명 변경 등등..)에 대한 피드백
3. 병합을 시도했으나 개인 노트북 메모리 에러가 떴습니다. 이거는 학교 서버를 사용하거나 해야하겠죠..!?
4. 향후 관측 데이터의 EDA는 어떻게 진행하는지 좋을지 의견 부탁드립니다. ex) 평균기온, 최고기온, 최저기온 중 어떤 값을 쓸지 아니면 모두 다 사용할지..

**Comment by parkseonga** [comment]
1. feature별로 제거한 데이터 컬럼들 중 중요도가 높은 컬럼인데 drop한 컬럼은 없지만 경제성장률 부분에서 중요도가 낮았던 컬럼까지 함께 사용한 것을 확인하고 제거하였습니다. 

2. 전처리 한 부분에서는 한우평균경매금액_주간평균과 돼지탕박경매금액_주간평균 컬럼은 모든 데이터에서 추출하셨는데 처음 한 번만 추출하면 될 것 같아요! 주간날짜 컬럼을 기준으로 결합해야하기 때문에 모든 데이터에서 주간날짜 컬럼만 동일하게 남기면 된다고 생각합니다.

3. 한우평균경매금액_주간평균을 기준으로 결합을 시도하여 메모리 에러가 발생했을수도 있을 것 같아요. 한우평균경매금액_주간평균이 아닌 주간날짜 컬럼을 기준으로 결합을 시도해야합니다.

4. 관측데이터 부분은 좀 더 보고 공유하겠습니다.

위 내용들을 수정한 부분은 commit하겠습니다. 확인부탁드려요! 고생하셨습니다:)

**Comment by iamcodingcat** [comment]
아하! 제가 자꾸 merge할때 기준칼럼을 헷갈리네요 ㅜㅜ 피드백 감사합니다!! 
수정 커밋 확인하는 대로 확인해보겠습니다 👍
